spring:
  profiles:
    active: dev

weather:
  api:
    key: ${WEATHER_API_KEY} # This Env variable is set in ~/.bashrc
    #We have commented because we are now storing the API URL in the database and using AppCache to retrieve it
    # url: "http://api.weatherstack.com/current?access_key={apiKey}&query={city}"