spring:
  mongodb:
    uri: mongodb+srv://gangwaryogendra_db_user:O2C8znYjBRpME6TQ@cluster0.hhfoyy6.mongodb.net/journaldb?retryWrites=true&w=majority&appName=Cluster0
    #uri: mongodb+srv://<UserName>:<Password>@cluster0.hhfoyy6.mongodb.net/journaldb?retryWrites=true&w=majority&appName=Cluster0
    #uri: ${MONGODB_URI} # This Env variable is set in ~/.bashrc

  data:
    mongodb:
      database: journaldb
      auto-index-creation: true

server:
    port: 8080
    servlet:
        context-path: /api/v1