spring:
  mongodb:
    uri: ${MONGODB_URI} # This Env variable is set in ~/.bashrc

  data:
    mongodb:
      database: journaldb
      auto-index-creation: true

server:
    port: 8080
    servlet:
        context-path: /api/v1